### ISSUE TITLE
Deployment 2020-2.0 checklist

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II-CSX/xf23id1_profiles#39]
## Previsit 
- [x] Make sure that the current latest _collection_ environments are pushed to all the bl machines
- [x] Make sure that the current latest _analysis_ environments are pushed to all the bl machines
- [x] Skim the IPython startup files in `profile_collection`
  - Check if it's safe to start `bsui` remotely (does it touch any hardware?) - use `git grep .put` or `git grep caput`
- [x] Check for outstanding PRs and issues on beamline repos
- [x] Check if beamline specific packages pushed to the BL machines
- [ ] (Optional) Enable CI

## Housekeeping 
- [x] Add BL staff to the BL GitHub organization as owners
- [x] Work with BL staff to commit any un-committed changes to their profiles
- [x] Tag the profile as-found as 2019C3.x
- [x] Discuss with BL staff which conda envs they want to keep/delete and perform the cleanup
- [x] Check/update the beamline's inventory with the BL staff (in https://github.com/NSLS-II/playbooks/blob/master/production)

## Test deployment 
- [x] Run profile against new environment
  - `BS_ENV=collection-2020-2.0rc7-1 bsui`
- [x] Update the profile as needed to run:
  - [x] Replace `.value` -> `.get()` if it's in a `Device`, or with `yield from bps.read()` if in a plan
  - [x] `history.sqlite` issue - see https://blueskyproject.io/bluesky/metadata.html#persistence-between-sessions
  - [x] potential issue with images in databroker V2
- [x] Run acceptance tests (if any) and run a representative set of scans for the beamline
- [x] Tag the updated profile as `2020C2.0`
- [x] Update BSUI via ansible to use the new environment (http://nsls-ii.github.io/deployment/upgrading-beamlines.html#change-bsui-s-default-environment)

**Comment by MikeHart85** [comment]
Misc notes from deployment:

- WS4 was not reachable; generally not used; we excluded it
- Removed jedi option exclusion from bsui
- Removed Qt Kicker message

**Comment by mrakitin** [comment]
The CSX beamline was successfully upgraded. Relevant commits:
-  Use nslsii instead of hxntools (https://github.com/NSLS-II-CSX/xf23id1_profiles/commit/2d99d801137287ac6e7c39b179ac5c8e2c6d48a9)
-  Change `.value` --> `.get()` (https://github.com/NSLS-II-CSX/xf23id1_profiles/commit/ca98495eb0ec6a9bbc238a8587c75d33c82e5353)
-  Comment out `install_qt_kicker` (https://github.com/NSLS-II-CSX/xf23id1_profiles/commit/51fb6c979d0b17f8ebe4e8681f555afaeb653cda)
-  Add a missing import of `ttime` (https://github.com/NSLS-II-CSX/xf23id1_profiles/commit/b4084d6220c5c2d4152b740d9c3b0897f0aabe80)
- merged and tested https://github.com/NSLS-II-CSX/xf23id1_profiles/pull/19

Playbooks update: https://github.com/NSLS-II/playbooks/pull/368.
