### ISSUE TITLE
Deployment 2021-1.0 checklist

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II-CSX/xf23id1_profiles#45]
## Current collection workstations

```
xf23id1-ws2  # main "workhorse" collection machine
xf23id1-ws1  # same as ws2, used tangentially for other activities but hot-swap backup for ws2
xf23id1-ws4  # same as ws2, used tangentially for other activities but hot-swap backup for ws2
```

## Previsit

- [x] Enable Azure-Pipelines CI
- [x] Make sure that the current latest environments are pushed to all the bl machines
- [x] Skim the IPython startup files in `profile_collection`
  - Check if it's safe to start `bsui` remotely (does it touch any hardware?) - use `git grep .put` or `git grep caput`
- [x] Check for outstanding PRs and issues on beamline repos
- [x] Branch https://github.com/NSLS-II/playbooks for the purpose of updating the CSX `current_env_tag` in the `production` file

## Housekeeping

- [x] Update `/opt/conda/.condarc`:
  ```yaml
  channel_priority: flexible
  channels:
    - nsls2forge
    - defaults
  create_default_packages:
    - anaconda-client
    - pip
  envs_dirs:
    - ~/conda_envs
    - /opt/conda_envs
  ssl_verify: false
  show_channel_urls: True
  ```
- [x] Update conda
  ```bash
  $ su - <your-controls-account>
  $ sudo su -
  # conda activate base  # should be activated by default, but just in case.
  # conda install conda -c defaults
  ```
- [x] Add BL staff to the BL GitHub organization as owners
- [x] Work with BL staff to commit any un-committed changes to their profiles
- [x] Tag the `profile_collection` repository as-found as `2020C2.1` and push to GitHub
   ```bash
   $ git tag 2020C2.1 -m "Before 2021C1.0 deployment"
   ```
- [x] Discuss with BL staff which conda envs they want to keep/delete and perform the cleanup
- [x] Check/update the beamline's workstation inventory with the BL staff (in https://github.com/NSLS-II/playbooks/blob/master/production)
- [x] In `~/.bashrc`, if necessary, update the logging environment variables to use directory `/var/log/bluesky/...` and add `umask 0002`.
  ```bash
  umask u=rwx,g=rwx,o=rx  # 0002
  export BLUESKY_LOG_FILE=/var/log/bluesky/bluesky.log
  export BLUESKY_IPYTHON_LOG_FILE=/var/log/bluesky/bluesky_ipython.log
  ```
  and (if needed) create that directory with the following permissions and ownership:
  ```bash
  # sudo mkdir /var/log/bluesky
  # sudo chown -Rv xf23id1:csx /var/log/bluesky
  # sudo chmod -Rv g+rws /var/log/bluesky
  ```
  Remember to `source ~/.bashrc`.
- [x] Remove explicit setting of ophyd logging level from the first startup script
- [x] Double-check that if there is an open PR removing handlers, it is merged (and tested).
- [x] Update vendored copy of `PersistentDict` to bug-fixed version (see the updated gist snippet: https://gist.github.com/jklynch/a4366b8900ec0c03883403455ae711b2).
- [x] (https://github.com/NSLS-II-CSX/xf23id1_profiles/issues/48) Make sure all repos have the BSD-3-Clause licenses (see https://github.com/NSLS-II-SRX/profile_collection/pull/16 as an example)

## Test deployment

- [x] Run profile against new environment
  ```bash
  $ BS_ENV=collection-2021-1.0 bsui
  ```
  It may be necessary to disable `jedi` in `ipython`. Add this to the `ipython` command line arguments in`bsui`:
  ```bash
  --IPCompleter.use_jedi=False
  ```
- [x] Update the profile as needed to run
- [x] Test databroker v2
  ```
  from databroker import catalog
  cat = catalog['csx']
  cat[-1].primary.read()
  ```
- [x] (https://github.com/NSLS-II-CSX/xf23id1_profiles/issues/49) Question about https://github.com/NSLS-II-CSX/xf23id1_profiles/blob/b4084d6220c5c2d4152b740d9c3b0897f0aabe80/profile_collection/startup/csx1/startup/detectors.py#L112
- [x] Run acceptance tests (if any) and run a representative set of scans for the beamline

## Finish

- [x] Tag the updated profile as `2021C1.0`
   ```bash
   $ git tag 2021C1.0 -m "After 2021C1.0 deployment"
   ```
- [x] Open and merge a PR against https://github.com/NSLS-II/playbooks setting `current_env_tag="2021-1.0"` for the CSX beamline (https://github.com/NSLS-II/playbooks/pull/424)
- [x] Update `bsui` via ansible to use the new environment (http://nsls-ii.github.io/deployment/upgrading-beamlines.html#change-bsui-s-default-environment)

**Comment by mrakitin** [comment]
Spent ~2.5 hours. Probably need to schedule not less than 3 hours next time.

**Comment by mrakitin** [comment]
We need to address a question about https://github.com/NSLS-II-CSX/xf23id1_profiles/blob/b4084d6220c5c2d4152b740d9c3b0897f0aabe80/profile_collection/startup/csx1/startup/detectors.py#L112.

**Comment by ambarb** [comment]
In initial comment, I altered it to be correct:
### From
xf23id1-ws1  # workstation for analysis for users, no xf account
### To
xf23id1-ws1  # same as ws2, used tangentially for other activities but hot-swap backup for ws2

After Tom Smith mounts the correct home directory for xf23id1 (hosted by beamline GPFS), then we should go back and make sure everything is like ws2

Attn @johnsinsheimer: just letting you know so we are all on the same page.

**Comment by mrakitin** [comment]
The deployment at CSX is done! Any follow-up questions will be communicated via Teams/emails.
